"""Fraud-model training, calibration, and serving decisions."""

from sentinelstream.models.calibration import (
    ProbabilityCalibrator,
    calibration_report,
    expected_calibration_error,
)
from sentinelstream.models.decision import (
    PredictionSignals,
    RecommendedAction,
    RiskDecision,
    RiskTier,
    ThresholdPolicy,
    make_decision,
)
from sentinelstream.models.evaluation import CostConfig, evaluate_scores
from sentinelstream.models.explainability import (
    Counterfactual,
    ExplainerUnavailableError,
    Explanation,
    ExplanationStore,
    FeatureContribution,
    FeatureImportance,
    GlobalExplanation,
    ReasonCode,
    build_reason_codes,
    explain_global,
    explain_local,
    explanation_stability,
    generate_counterfactuals,
)
from sentinelstream.models.hybrid import (
    AblationExperiment,
    AblationResult,
    CalibrationValidation,
    HybridFraudEngine,
    HybridResult,
    HybridSignals,
    HybridSource,
    HybridWeights,
    ProfileRisk,
    prioritise_alerts,
    validate_calibration,
)
from sentinelstream.models.thresholding import (
    CostModel,
    ThresholdOptimizationResult,
    expected_financial_cost,
    optimize_threshold,
)
from sentinelstream.models.training import BaselineRun, train_baselines

__all__ = [
    "BaselineRun",
    "AblationExperiment",
    "AblationResult",
    "CalibrationValidation",
    "CostConfig",
    "CostModel",
    "Counterfactual",
    "Explanation",
    "ExplanationStore",
    "ExplainerUnavailableError",
    "FeatureContribution",
    "FeatureImportance",
    "GlobalExplanation",
    "HybridFraudEngine",
    "HybridResult",
    "HybridSignals",
    "HybridSource",
    "HybridWeights",
    "ProfileRisk",
    "ReasonCode",
    "build_reason_codes",
    "explain_global",
    "explain_local",
    "explanation_stability",
    "generate_counterfactuals",
    "PredictionSignals",
    "ProbabilityCalibrator",
    "RecommendedAction",
    "RiskDecision",
    "RiskTier",
    "ThresholdOptimizationResult",
    "ThresholdPolicy",
    "calibration_report",
    "evaluate_scores",
    "expected_calibration_error",
    "expected_financial_cost",
    "make_decision",
    "optimize_threshold",
    "prioritise_alerts",
    "train_baselines",
    "validate_calibration",
]
